DROP TABLE TRAIN_EMP;

CREATE TABLE TRAIN_EMP
(
  EMPID   NUMERIC(10,0) NOT NULL,
  ORGID   NUMERIC(10,0) NOT NULL,
  EMPCODE VARCHAR(32) NOT NULL,
  EMPNAME VARCHAR(64) NOT NULL,
  SEX     VARCHAR(1),
  BIRTHDAY TIMESTAMP,
  POSTCODE CHAR(6),
  ADDRESS  VARCHAR(128),
  PHONE    VARCHAR(32),
  WAGE    NUMERIC(8,0) DEFAULT 2000,
  PRIMARY KEY (EMPID)

);
COMMENT ON COLUMN TRAIN_EMP.EMPID IS '用户ID';
COMMENT ON COLUMN TRAIN_EMP.ORGID IS '机构ID';
COMMENT ON COLUMN TRAIN_EMP.EMPCODE IS '用户编号';
COMMENT ON COLUMN TRAIN_EMP.EMPNAME IS '用户姓名';
COMMENT ON COLUMN TRAIN_EMP.SEX IS '性别';
COMMENT ON COLUMN TRAIN_EMP.BIRTHDAY IS '出生日期';
COMMENT ON COLUMN TRAIN_EMP.POSTCODE IS '邮编';
COMMENT ON COLUMN TRAIN_EMP.ADDRESS IS '地址';
COMMENT ON COLUMN TRAIN_EMP.PHONE IS '电话';
COMMENT ON COLUMN TRAIN_EMP.WAGE IS '工资';

INSERT INTO TRAIN_EMP (EMPID, ORGID, EMPCODE, EMPNAME, SEX, BIRTHDAY, POSTCODE, ADDRESS, PHONE, WAGE) 
		VALUES( 1, 1, '001', '张三丰', 'M', '1957-01-25', '710070', '北京海淀区中关村大街01号', '80080001',2000);
INSERT INTO TRAIN_EMP (EMPID, ORGID, EMPCODE, EMPNAME, SEX, BIRTHDAY, POSTCODE, ADDRESS, PHONE, WAGE) 
		VALUES( 2, 1, '002', '张无忌', 'M', '1972-11-30','710071', '上海张江高科技园区碧波路456号4层', '80080002',2000);
INSERT INTO TRAIN_EMP (EMPID, ORGID, EMPCODE, EMPNAME, SEX, BIRTHDAY, POSTCODE, ADDRESS, PHONE, WAGE) 
		VALUES( 3, 1, '003', '张小宝', 'M', '1974-05-19', '710072', '北京市海淀区彩和坊路8号天创科技大厦东门1301室', '80080003',2000);
INSERT INTO TRAIN_EMP (EMPID, ORGID, EMPCODE, EMPNAME, SEX, BIRTHDAY, POSTCODE, ADDRESS, PHONE, WAGE) 
		VALUES( 4, 1, '004', '赵大海', 'M', '1977-07-08', '710073', '广州市天河区体育东路', '80080004',2000);
INSERT INTO TRAIN_EMP (EMPID, ORGID, EMPCODE, EMPNAME, SEX, BIRTHDAY, POSTCODE, ADDRESS, PHONE, WAGE) 
		VALUES( 5, 1, '005', '赵小新', 'M', '1956-04-19', '710074', '北京海淀区中关村22号', '80080005',2000);
INSERT INTO TRAIN_EMP (EMPID, ORGID, EMPCODE, EMPNAME, SEX, BIRTHDAY, POSTCODE, ADDRESS, PHONE, WAGE) 
		VALUES( 6, 1, '006', '李中正', 'F', '1956-01-25', '610000', '成都高新区创新中心起步区府河基地高朋大道12号B座209-210室', '88080006',2000);
INSERT INTO TRAIN_EMP (EMPID, ORGID, EMPCODE, EMPNAME, SEX, BIRTHDAY, POSTCODE, ADDRESS, PHONE, WAGE) 
		VALUES( 7, 1, '007', '李亚南', 'M', '1966-12-24', '410000', '长沙市国家高新技术开发区火炬村M2组团金荣科技园7楼', '80080007',2000);
INSERT INTO TRAIN_EMP (EMPID, ORGID, EMPCODE, EMPNAME, SEX, BIRTHDAY, POSTCODE, ADDRESS, PHONE, WAGE) 
		VALUES( 8, 1, '008', '程丰富', 'M', '1976-11-19', '320000', '南京市中山南路387号侨宁公寓北楼601室', '80080008',2000);
INSERT INTO TRAIN_EMP (EMPID, ORGID, EMPCODE, EMPNAME, SEX, BIRTHDAY, POSTCODE, ADDRESS, PHONE, WAGE) 
		VALUES( 9, 1, '009', '陈三笑', 'M', '1954-11-20', '100000', '北京海淀区中关村26号', '80080009',2000);
INSERT INTO TRAIN_EMP (EMPID, ORGID, EMPCODE, EMPNAME, SEX, BIRTHDAY, POSTCODE, ADDRESS, PHONE, WAGE) 
		VALUES( 10, 1, '010', '吴亚太', 'M', '1968-11-19', '100000', '北京海淀区中关村东路421号', '80080010',2000);
INSERT INTO TRAIN_EMP (EMPID, ORGID, EMPCODE, EMPNAME, SEX, BIRTHDAY, POSTCODE, ADDRESS, PHONE, WAGE) 
		VALUES( 11, 1, '011', '吴小三', 'F', '1970-04-08', '100000', '上海张江高科技园区碧波路456号4层', '80080011',2000);
INSERT INTO TRAIN_EMP (EMPID, ORGID, EMPCODE, EMPNAME, SEX, BIRTHDAY, POSTCODE, ADDRESS, PHONE, WAGE) 
		VALUES( 12, 1, '012', '雷小洛', 'M', '1942-09-19', '100000', '北京海淀区中关村东路22号', '80080012',2000);
COMMIT;

DELETE FROM EOS_UNIQUE_TABLE WHERE NAME ='TrainEmp.empid';
INSERT INTO EOS_UNIQUE_TABLE(NAME, CODE) VALUES('TrainEmp.empid', 12);
COMMIT;

DROP TABLE TRAIN_ORG;
CREATE TABLE TRAIN_ORG 
 (
   ORGID         NUMERIC(10,0)     NOT NULL,
   ORGCODE       VARCHAR(20)	NOT NULL,
   ORGNAME       VARCHAR(128)  NOT NULL,
   ORGADDRESS    VARCHAR(128),
   PARENTORGID   NUMERIC(10,0),
   PRIMARY KEY (ORGID)
);

COMMENT ON COLUMN TRAIN_ORG.ORGID IS '机构ID';
COMMENT ON COLUMN TRAIN_ORG.ORGCODE IS '机构编号';
COMMENT ON COLUMN TRAIN_ORG.ORGNAME IS '机构名称';
COMMENT ON COLUMN TRAIN_ORG.ORGADDRESS IS '机构地址';
COMMENT ON COLUMN TRAIN_ORG.PARENTORGID IS '父机构ID';

INSERT INTO TRAIN_ORG (ORGID, ORGCODE, ORGNAME, ORGADDRESS, PARENTORGID) VALUES(1, 'head', '总部', '上海', NULL);
INSERT INTO TRAIN_ORG (ORGID, ORGCODE, ORGNAME, ORGADDRESS, PARENTORGID) VALUES(2, 'shanghai', '上海分公司', '浦东', 1);
INSERT INTO TRAIN_ORG (ORGID, ORGCODE, ORGNAME, ORGADDRESS, PARENTORGID) VALUES(3, 'beijing', '北京分公司', '北京', 1);
INSERT INTO TRAIN_ORG (ORGID, ORGCODE, ORGNAME, ORGADDRESS, PARENTORGID) VALUES(4, 'rd', '上海研发中心', '浦东', 2);
DELETE FROM EOS_UNIQUE_TABLE WHERE NAME ='TrainOrg.orgid';
INSERT INTO EOS_UNIQUE_TABLE(NAME, CODE) VALUES('TrainOrg.orgid', 4);

COMMIT;


DROP TABLE TRAIN_CONTACTS;
CREATE TABLE TRAIN_CONTACTS  (
   CONTACTID           NUMERIC(10,0)  NOT NULL,
   EMPID               NUMERIC(10,0),
   CONTACTNAME         VARCHAR(20)  NOT NULL,
   RELATION            VARCHAR(20),
   PHONE               VARCHAR(20),
   POSTCODE            CHAR(6),
   ADDRESS             VARCHAR(128),
   EMAIL               VARCHAR(128),
   PRIMARY KEY (CONTACTID)
);

COMMENT ON COLUMN TRAIN_CONTACTS.CONTACTID IS '联系人ID';
COMMENT ON COLUMN TRAIN_CONTACTS.EMPID IS '员工ID';
COMMENT ON COLUMN TRAIN_CONTACTS.CONTACTNAME IS '联系人姓名';
COMMENT ON COLUMN TRAIN_CONTACTS.RELATION IS '关系';
COMMENT ON COLUMN TRAIN_CONTACTS.PHONE IS '联系人电话';
COMMENT ON COLUMN TRAIN_CONTACTS.POSTCODE IS '联系人邮编';
COMMENT ON COLUMN TRAIN_CONTACTS.ADDRESS IS '联系人地址';
COMMENT ON COLUMN TRAIN_CONTACTS.EMAIL IS '联系人信箱';

COMMIT;


DROP TABLE TRAIN_EXPENSEINFO;
CREATE TABLE TRAIN_EXPENSEINFO
(
  EXPID          NUMERIC(10, 0) NOT NULL,
  EXPCODE        VARCHAR(64) NOT NULL,
  EMPID   NUMERIC(10,0) NOT NULL,
  EXPNAME        VARCHAR(64) NOT NULL,
  EXPDATE        TIMESTAMP,
  EXPMONEY       NUMERIC(12, 2) NOT NULL,
  REASON         VARCHAR(255),
  ISBUDGETITEM   CHAR(1),
  BENEFITORGID   NUMERIC(10, 0),
  MANAGER		 VARCHAR(64),
  MANAGER_ADVICE VARCHAR(255),
  AUDITOR		 VARCHAR(64),
  AUDITOR_ADVICE VARCHAR(255),
  PROCESSINSTID  NUMERIC(20, 0),
  PRIMARY KEY (EXPID)
 );
-- Add comments to the columns 
comment on column TRAIN_EXPENSEINFO.EXPID is '报销单ID';
comment on column TRAIN_EXPENSEINFO.EXPCODE is '报销单编号';
comment on column TRAIN_EXPENSEINFO.EMPID is '报销人ID';
comment on column TRAIN_EXPENSEINFO.EXPNAME is '报销人姓名';
comment on column TRAIN_EXPENSEINFO.EXPDATE is '报销日期';
comment on column TRAIN_EXPENSEINFO.EXPMONEY is '报销金额';
comment on column TRAIN_EXPENSEINFO.REASON is '报销原因';
comment on column TRAIN_EXPENSEINFO.ISBUDGETITEM is '是否预算内项目';
comment on column TRAIN_EXPENSEINFO.BENEFITORGID is '受益部门';
comment on column TRAIN_EXPENSEINFO.MANAGER is '部门经理';
comment on column TRAIN_EXPENSEINFO.MANAGER_ADVICE is '部门经理意见';
comment on column TRAIN_EXPENSEINFO.AUDITOR is '财务审核';
comment on column TRAIN_EXPENSEINFO.AUDITOR_ADVICE is '财务审核意见';
comment on column TRAIN_EXPENSEINFO.PROCESSINSTID is '流程实例ID';

--Create table
DROP TABLE TRAIN_WF_TRACK;
CREATE TABLE TRAIN_WF_TRACK
( 
  TRACK_ID       	NUMERIC(10, 0), 
  WORKITEM_ID 		NUMERIC(20,0),
  PROCESSINST_ID	NUMERIC(20, 0),
  ASSISTANT_ID		NUMERIC(10,0),
  ASSISTANT_NAME	VARCHAR(64),
  DEALDATE		TIMESTAMP,
  DEALRESULT     	CHAR(1),
  DEALOPINION		VARCHAR(255),
  PRIMARY KEY (TRACK_ID)
);
-- Add comments to the columns 
comment on column TRAIN_WF_TRACK.TRACK_ID is '流转ID';
comment on column TRAIN_WF_TRACK.WORKITEM_ID is '工作项ID';
comment on column TRAIN_WF_TRACK.PROCESSINST_ID is '流程实例ID';
comment on column TRAIN_WF_TRACK.ASSISTANT_ID is '审批人ID';
comment on column TRAIN_WF_TRACK.ASSISTANT_NAME is '审批人姓名';
comment on column TRAIN_WF_TRACK.DEALDATE is '审批日期';
comment on column TRAIN_WF_TRACK.DEALRESULT is '审批结果';
comment on column TRAIN_WF_TRACK.DEALOPINION is '审批意见';

delete from eos_dict_entry where dicttypeid='TRAIN_SEX';
delete from eos_dict_type where dicttypeid='TRAIN_SEX';
insert into eos_dict_type(dicttypeid,dicttypename,rank) values('TRAIN_SEX','性别',1);
insert into eos_dict_entry(dicttypeid,dictid,dictname) values('TRAIN_SEX','F','女');
insert into eos_dict_entry(dicttypeid,dictid,dictname) values('TRAIN_SEX','M','男');
insert into eos_dict_entry(dicttypeid,dictid,dictname) values('TRAIN_SEX','U','未知');


delete from eos_dict_entry where dicttypeid='TRAIN_DEALRESULT';
delete from eos_dict_type where dicttypeid='TRAIN_DEALRESULT';
insert into eos_dict_type(dicttypeid,dicttypename,rank) values('TRAIN_DEALRESULT','同意否',1);
insert into eos_dict_entry(dicttypeid,dictid,dictname) values('TRAIN_DEALRESULT','0','不同意');
insert into eos_dict_entry(dicttypeid,dictid,dictname) values('TRAIN_DEALRESULT','1','同意');
commit;