DROP TABLE IF EXISTS TRAIN_EMP;
CREATE TABLE TRAIN_EMP
(
  EMPID   DECIMAL(10,0) NOT NULL COMMENT '用户ID',
  ORGID   DECIMAL(10,0) NOT NULL COMMENT '机构ID',
  EMPCODE VARCHAR(32) NOT NULL COMMENT '用户编号',
  EMPNAME VARCHAR(64) NOT NULL COMMENT '用户姓名',
  SEX     VARCHAR(1) COMMENT '性别',
  BIRTHDAY DATETIME COMMENT '出生日期',
  POSTCODE CHAR(6) COMMENT '邮编',
  ADDRESS  VARCHAR(128) COMMENT '地址',
  PHONE    VARCHAR(32) COMMENT '电话',
  WAGE    DECIMAL(8,0) DEFAULT 2000 COMMENT '工资',
  PRIMARY KEY (EMPID)

);

INSERT INTO TRAIN_EMP (EMPID, ORGID, EMPCODE, EMPNAME, SEX, BIRTHDAY, POSTCODE, ADDRESS, PHONE, WAGE) 
		VALUES( 1, 1, '001', '张三丰', 'M', '1957-01-25', '710070', '北京海淀区中关村大街01号', '80080001',2000);
INSERT INTO TRAIN_EMP (EMPID, ORGID, EMPCODE, EMPNAME, SEX, BIRTHDAY, POSTCODE, ADDRESS, PHONE, WAGE) 
		VALUES( 2, 1, '002', '张无忌', 'M', '1972-11-30','710071', '上海张江高科技园区碧波路456号4层', '80080002',2000);
INSERT INTO TRAIN_EMP (EMPID, ORGID, EMPCODE, EMPNAME, SEX, BIRTHDAY, POSTCODE, ADDRESS, PHONE, WAGE) 
		VALUES( 3, 1, '003', '张小宝', 'M', '1974-05-19', '710072', '北京市海淀区彩和坊路8号天创科技大厦东门1301室', '80080003',2000);
INSERT INTO TRAIN_EMP (EMPID, ORGID, EMPCODE, EMPNAME, SEX, BIRTHDAY, POSTCODE, ADDRESS, PHONE, WAGE) 
		VALUES( 4, 1, '004', '赵大海', 'M', '1977-07-08', '710073', '广州市天河区体育东路', '80080004',2000);
INSERT INTO TRAIN_EMP (EMPID, ORGID, EMPCODE, EMPNAME, SEX, BIRTHDAY, POSTCODE, ADDRESS, PHONE, WAGE) 
		VALUES( 5, 1, '005', '赵小新', 'M', '1956-04-19', '710074', '北京海淀区中关村22号', '80080005',2000);
INSERT INTO TRAIN_EMP (EMPID, ORGID, EMPCODE, EMPNAME, SEX, BIRTHDAY, POSTCODE, ADDRESS, PHONE, WAGE) 
		VALUES( 6, 1, '006', '李中正', 'F', '1956-01-25', '610000', '成都高新区创新中心起步区府河基地高朋大道12号B座209-210室', '88080006',2000);
INSERT INTO TRAIN_EMP (EMPID, ORGID, EMPCODE, EMPNAME, SEX, BIRTHDAY, POSTCODE, ADDRESS, PHONE, WAGE) 
		VALUES( 7, 1, '007', '李亚南', 'M', '1966-12-24', '410000', '长沙市国家高新技术开发区火炬村M2组团金荣科技园7楼', '80080007',2000);
INSERT INTO TRAIN_EMP (EMPID, ORGID, EMPCODE, EMPNAME, SEX, BIRTHDAY, POSTCODE, ADDRESS, PHONE, WAGE) 
		VALUES( 8, 1, '008', '程丰富', 'M', '1976-11-19', '320000', '南京市中山南路387号侨宁公寓北楼601室', '80080008',2000);
INSERT INTO TRAIN_EMP (EMPID, ORGID, EMPCODE, EMPNAME, SEX, BIRTHDAY, POSTCODE, ADDRESS, PHONE, WAGE) 
		VALUES( 9, 1, '009', '陈三笑', 'M', '1954-11-20', '100000', '北京海淀区中关村26号', '80080009',2000);
INSERT INTO TRAIN_EMP (EMPID, ORGID, EMPCODE, EMPNAME, SEX, BIRTHDAY, POSTCODE, ADDRESS, PHONE, WAGE) 
		VALUES( 10, 1, '010', '吴亚太', 'M', '1968-11-19', '100000', '北京海淀区中关村东路421号', '80080010',2000);
INSERT INTO TRAIN_EMP (EMPID, ORGID, EMPCODE, EMPNAME, SEX, BIRTHDAY, POSTCODE, ADDRESS, PHONE, WAGE) 
		VALUES( 11, 1, '011', '吴小三', 'F', '1970-04-08', '100000', '上海张江高科技园区碧波路456号4层', '80080011',2000);
INSERT INTO TRAIN_EMP (EMPID, ORGID, EMPCODE, EMPNAME, SEX, BIRTHDAY, POSTCODE, ADDRESS, PHONE, WAGE) 
		VALUES( 12, 1, '012', '雷小洛', 'M', '1942-09-19', '100000', '北京海淀区中关村东路22号', '80080012',2000);
COMMIT;

DELETE FROM EOS_UNIQUE_TABLE WHERE NAME ='TrainEmp.empid';
INSERT INTO EOS_UNIQUE_TABLE(NAME, CODE) VALUES('TrainEmp.empid', 12);
COMMIT;

DROP TABLE IF EXISTS TRAIN_ORG;
CREATE TABLE TRAIN_ORG 
 (
   ORGID         DECIMAL(10,0)     NOT NULL COMMENT '机构ID',
   ORGCODE       VARCHAR(20) NOT NULL COMMENT '机构编号',
   ORGNAME       VARCHAR(128)  NOT NULL COMMENT '机构名称',
   ORGADDRESS    VARCHAR(128) COMMENT '机构地址',
   PARENTORGID   DECIMAL(10,0) COMMENT '父机构ID',
   PRIMARY KEY (ORGID)
);

INSERT INTO TRAIN_ORG (ORGID, ORGCODE, ORGNAME, ORGADDRESS, PARENTORGID) VALUES(1, 'head', '总部', '上海', NULL);
INSERT INTO TRAIN_ORG (ORGID, ORGCODE, ORGNAME, ORGADDRESS, PARENTORGID) VALUES(2, 'shanghai', '上海分公司', '浦东', 1);
INSERT INTO TRAIN_ORG (ORGID, ORGCODE, ORGNAME, ORGADDRESS, PARENTORGID) VALUES(3, 'beijing', '北京分公司', '北京', 1);
INSERT INTO TRAIN_ORG (ORGID, ORGCODE, ORGNAME, ORGADDRESS, PARENTORGID) VALUES(4, 'rd', '上海研发中心', '浦东', 2);
DELETE FROM EOS_UNIQUE_TABLE WHERE NAME ='TrainOrg.orgid';
INSERT INTO EOS_UNIQUE_TABLE(NAME, CODE) VALUES('TrainOrg.orgid', 4);


DROP TABLE IF EXISTS TRAIN_CONTACTS;
CREATE TABLE TRAIN_CONTACTS  (
   CONTACTID           DECIMAL(10,0)  NOT NULL COMMENT '联系人ID',
   EMPID               DECIMAL(10,0) COMMENT '员工ID',
   CONTACTNAME         VARCHAR(20)  NOT NULL COMMENT '联系人姓名',
   RELATION            VARCHAR(20) COMMENT '关系',
   PHONE               VARCHAR(20) COMMENT '联系人电话',
   POSTCODE            CHAR(6) COMMENT '联系人邮编',
   ADDRESS             VARCHAR(128) COMMENT '联系人地址',
   EMAIL               VARCHAR(128) COMMENT '联系人信箱',
   PRIMARY KEY (CONTACTID)
);

COMMIT;


DROP TABLE IF EXISTS TRAIN_EXPENSEINFO;
CREATE TABLE TRAIN_EXPENSEINFO
(
  EXPID          DECIMAL(10, 0) NOT NULL COMMENT '报销单ID',
  EXPCODE        VARCHAR(64) NOT NULL COMMENT '报销单编号',
  EMPID   DECIMAL(10,0) NOT NULL COMMENT '报销人ID',
  EXPNAME        VARCHAR(64) NOT NULL COMMENT '报销人姓名',
  EXPDATE        DATETIME COMMENT '报销日期',
  EXPMONEY       DECIMAL(12, 2) NOT NULL COMMENT '报销金额',
  REASON         VARCHAR(255) COMMENT '报销原因',
  ISBUDGETITEM   CHAR(1) COMMENT '是否预算内项目',
  BENEFITORGID   DECIMAL(10, 0) COMMENT '受益部门',
  MANAGER		 VARCHAR(64) COMMENT '部门经理',
  MANAGER_ADVICE VARCHAR(255) COMMENT '部门经理意见',
  AUDITOR		 VARCHAR(64) COMMENT '财务审核',
  AUDITOR_ADVICE VARCHAR(255) COMMENT '财务审核意见',
  PROCESSINSTID  DECIMAL(20, 0) COMMENT '流程实例ID',
  PRIMARY KEY (EXPID)
 );

DROP TABLE IF EXISTS TRAIN_WF_TRACK;
CREATE TABLE TRAIN_WF_TRACK
( 
  TRACK_ID       	DECIMAL(10, 0) COMMENT '流转ID', 
  WORKITEM_ID 		DECIMAL(20,0) COMMENT '工作项ID',
  PROCESSINST_ID	DECIMAL(20, 0) COMMENT '流程实例ID',
  ASSISTANT_ID		DECIMAL(10,0) COMMENT '审批人ID',
  ASSISTANT_NAME	VARCHAR(64) COMMENT '审批人姓名',
  DEALDATE		DATETIME COMMENT '审批日期',
  DEALRESULT     	CHAR(1) COMMENT '审批结果',
  DEALOPINION		VARCHAR(255) COMMENT '审批意见',
  PRIMARY KEY (TRACK_ID)
);

delete from eos_dict_entry where dicttypeid='TRAIN_SEX';
delete from eos_dict_type where dicttypeid='TRAIN_SEX';
insert into eos_dict_type(dicttypeid,dicttypename,rank) values('TRAIN_SEX','性别',1);
insert into eos_dict_entry(dicttypeid,dictid,dictname) values('TRAIN_SEX','F','女');
insert into eos_dict_entry(dicttypeid,dictid,dictname) values('TRAIN_SEX','M','男');
insert into eos_dict_entry(dicttypeid,dictid,dictname) values('TRAIN_SEX','U','未知');


delete from eos_dict_entry where dicttypeid='TRAIN_DEALRESULT';
delete from eos_dict_type where dicttypeid='TRAIN_DEALRESULT';
insert into eos_dict_type(dicttypeid,dicttypename,rank) values('TRAIN_DEALRESULT','同意否',1);
insert into eos_dict_entry(dicttypeid,dictid,dictname) values('TRAIN_DEALRESULT','0','不同意');
insert into eos_dict_entry(dicttypeid,dictid,dictname) values('TRAIN_DEALRESULT','1','同意');

commit;